### ISSUE TITLE
error during build: RollupError: "PUBLIC_API_URL" is not exported by "$env/static/public"

### ISSUE THREAD

**Issue by Simon-Piquemal** [TMRRWinc/caspr#2]
**Describe the bug**
`vite v4.4.8 building SSR bundle for production...
transforming (102) src/lib/data/localdb.ts12:04:25 [vite-plugin-svelte] /node_modules/@lottiefiles/svelte-lottie-player/src/components/Controls.svelte:231:6 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
229:   {#each layout as item}
230:     {#if item === 'playpause'}
231:       <div class="btn" on:click="{togglePlay}" class:active="{isPlaying || isPaused}">
           ^
232:         {#if isPlaying}
233:           <svg {...ICON_SIZE}>
12:04:25 [vite-plugin-svelte] /node_modules/@lottiefiles/svelte-lottie-player/src/components/Controls.svelte:244:6 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
242:       </div>
243:     {:else if item === 'stop'}
244:       <div class="btn" on:click="{stop}" class:active="{isStopped}">
           ^
245:         <svg {...ICON_SIZE}>
246:           <path
12:04:25 [vite-plugin-svelte] /node_modules/@lottiefiles/svelte-lottie-player/src/components/Controls.svelte:269:6 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
267:       />
268:     {:else if item === 'loop'}
269:       <div class="btn" on:click="{toggleLooping}" class:active="{loop}">
           ^
270:         <svg {...ICON_SIZE}>
271:           <path
12:04:25 [vite-plugin-svelte] /node_modules/@lottiefiles/svelte-lottie-player/src/components/Controls.svelte:317:6 A11y: on:mouseover must be accompanied by on:focus
315:       </div>
316:     {:else if item === 'snapshot'}
317:       <div
           ^
318:         class=""
319:         on:mouseout="{() => currentState === PlayerState.Frozen && play()}"
12:04:25 [vite-plugin-svelte] /node_modules/@lottiefiles/svelte-lottie-player/src/components/Controls.svelte:317:6 A11y: on:mouseout must be accompanied by on:blur
315:       </div>
316:     {:else if item === 'snapshot'}
317:       <div
           ^
318:         class=""
319:         on:mouseout="{() => currentState === PlayerState.Frozen && play()}"
12:04:25 [vite-plugin-svelte] /node_modules/@lottiefiles/svelte-lottie-player/src/components/Controls.svelte:351:6 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
349:       </div>
350:     {:else if item === 'zoom'}
351:       <div class="btn" on:click="{onToggleZoom}">
           ^
352:         {#if isZoomed}
353:           <svg {...ICON_SIZE}>
12:04:25 [vite-plugin-svelte] /node_modules/@lottiefiles/svelte-lottie-player/src/components/Controls.svelte:399:8 A11y: on:mouseover must be accompanied by on:focus
397:     {:else if item === 'frame'}
398:       <div class="">
399:         <input
             ^
400:           class="frame-number"
401:           type="text"
12:04:25 [vite-plugin-svelte] /node_modules/@lottiefiles/svelte-lottie-player/src/components/Controls.svelte:399:8 A11y: on:mouseout must be accompanied by on:blur
397:     {:else if item === 'frame'}
398:       <div class="">
399:         <input
             ^
400:           class="frame-number"
401:           type="text"
12:04:25 [vite-plugin-svelte] /node_modules/@lottiefiles/svelte-lottie-player/src/components/Controls.svelte:410:6 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
408:       </div>
409:     {:else if item === 'nextFrame'}
410:       <div class="btn" on:click="{onNextFrame}">
           ^
411:         <svg {...ICON_SIZE}>
412:           <path
12:04:25 [vite-plugin-svelte] /node_modules/@lottiefiles/svelte-lottie-player/src/components/Controls.svelte:420:6 A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
418:       </div>
419:     {:else if item === 'previousFrame'}
420:       <div class="btn" on:click="{oPreviousFrame}">
           ^
421:         <svg {...ICON_SIZE}>
422:           <path d="M22 4.5a1.4 1.4 0 00-2.1-1.2l-13 7.5a1.4 1.4 0 000 2.4l13 7.5a1.4 1.4 0 002.1-1.2z"></path>
transforming (118) node_modules/@lottiefiles/svelte-lottie-player/src/components/Controls.svelte12:04:25 [vite-plugin-svelte] /node_modules/@lottiefiles/svelte-lottie-player/src/components/Popover.svelte:82:0 A11y: on:mouseover must be accompanied by on:focus
80: </style>
81: 
82: <div
    ^
83:   class="popover"
84:   on:mousedown
12:04:25 [vite-plugin-svelte] /node_modules/@lottiefiles/svelte-lottie-player/src/components/Popover.svelte:82:0 A11y: on:mouseout must be accompanied by on:blur
80: </style>
81: 
82: <div
    ^
83:   class="popover"
84:   on:mousedown
✓ 127 modules transformed.
✓ built in 1.52s
"PUBLIC_API_URL" is not exported by "$env/static/public", imported by "src/lib/services/app.ts".
file: /Users/simonpiquemal/Documents/GitHub/caspr1/src/lib/services/app.ts:1:9
1: import { PUBLIC_API_URL } from '$env/static/public';
            ^
2: 
3: export const checkOnlineStatus = async () => {
error during build:
RollupError: "PUBLIC_API_URL" is not exported by "$env/static/public", imported by "src/lib/services/app.ts".
    at error (file:///Users/simonpiquemal/Documents/GitHub/caspr1/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
    at Module.error (file:///Users/simonpiquemal/Documents/GitHub/caspr1/node_modules/rollup/dist/es/shared/node-entry.js:13604:16)
    at Module.traceVariable (file:///Users/simonpiquemal/Documents/GitHub/caspr1/node_modules/rollup/dist/es/shared/node-entry.js:14029:29)
    at ModuleScope.findVariable (file:///Users/simonpiquemal/Documents/GitHub/caspr1/node_modules/rollup/dist/es/shared/node-entry.js:12547:39)
    at ReturnValueScope.findVariable (file:///Users/simonpiquemal/Documents/GitHub/caspr1/node_modules/rollup/dist/es/shared/node-entry.js:7082:38)
    at ChildScope.findVariable (file:///Users/simonpiquemal/Documents/GitHub/caspr1/node_modules/rollup/dist/es/shared/node-entry.js:7082:38)
    at BlockScope.findVariable (file:///Users/simonpiquemal/Documents/GitHub/caspr1/node_modules/rollup/dist/es/shared/node-entry.js:7082:38)
    at Identifier.bind (file:///Users/simonpiquemal/Documents/GitHub/caspr1/node_modules/rollup/dist/es/shared/node-entry.js:8267:40)
    at CallExpression.bind (file:///Users/simonpiquemal/Documents/GitHub/caspr1/node_modules/rollup/dist/es/shared/node-entry.js:5846:28)
    at CallExpression.bind (file:///Users/simonpiquemal/Documents/GitHub/caspr1/node_modules/rollup/dist/es/shared/node-entry.js:9833:15)
       Error beforeBuildCommand `npm run build` failed with exit code 1`
       
       
**To Reproduce**
1. Clone depo
2. Npm init / npm i ( "yup": "^1.2.0" )
3. npm run tauri build

**Expected behavior**
I think there's a problem with the package versions, especially "yup". 

**Desktop (please complete the following information):**
 - OS: MAC M1
 - Version M1

**Comment by shawnvogt** [comment]
Hi @Simon-Piquemal
You will need to add a .env file to the root of your project with the following content
```.env
# Public
PUBLIC_API_URL=<a URL that will respond to ping>
```
I will update the readme file to include this step and update the yup version in the package.json file 
Thank you for bringing these issues to our attention.

**Comment by Simon-Piquemal** [comment]
thank you for replying so quickly I'll test again and get back to you if I still have a problem.  :) @shawnvogt 😃
